name: mars
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - dgl
  - rdkit
  - numpy<2.0
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - pip:
      - tensorboard
      - torchdata==0.9.0